// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgWY5_T3CBs60delGLTGUW38eLSQ-tPU8',
    appId: '1:146606424807:web:949090acf4cd830b7dd842',
    messagingSenderId: '146606424807',
    projectId: 'paqufinal',
    authDomain: 'paqufinal.firebaseapp.com',
    storageBucket: 'paqufinal.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3Tvx8R1E3lXM5Yqhr0J9AGqMjA8-BY-I',
    appId: '1:146606424807:android:cc3933ed1bd6fcab7dd842',
    messagingSenderId: '146606424807',
    projectId: 'paqufinal',
    storageBucket: 'paqufinal.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA21dXoAapTNdfWY34moRkmkOIgby5uCBA',
    appId: '1:146606424807:ios:d77bd60dcea2a83e7dd842',
    messagingSenderId: '146606424807',
    projectId: 'paqufinal',
    storageBucket: 'paqufinal.firebasestorage.app',
    iosBundleId: 'com.example.paqufinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA21dXoAapTNdfWY34moRkmkOIgby5uCBA',
    appId: '1:146606424807:ios:d77bd60dcea2a83e7dd842',
    messagingSenderId: '146606424807',
    projectId: 'paqufinal',
    storageBucket: 'paqufinal.firebasestorage.app',
    iosBundleId: 'com.example.paqufinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgWY5_T3CBs60delGLTGUW38eLSQ-tPU8',
    appId: '1:146606424807:web:1263347ee832e1fa7dd842',
    messagingSenderId: '146606424807',
    projectId: 'paqufinal',
    authDomain: 'paqufinal.firebaseapp.com',
    storageBucket: 'paqufinal.firebasestorage.app',
  );
}
